export const listStyles = {
    swipeLeft: {
        padding: '10px 30px',
        width: '100%',
        height: 80,
        marginTop: '-10px',
        textAlign: 'right',
        borderRadius: 8,
        flexDirection: 'row-reverse',
        display: 'inline-flex',
        alignItems: 'center',
        color: '#fff',
        backgroundColor: '#44c5a7',
    },
    swipeRight: {
        padding: '10px 30px',
        width: '100%',
        height: 80,
        marginTop: '-10px',
        textAlign: 'right',
        borderRadius: 8,
        flexDirection: 'initial',
        display: 'inline-flex',
        alignItems: 'center',
        color: '#fff',
        backgroundColor: '#f07f0a',
    },
};